# Generated by Django 5.0.6 on 2024-07-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datememo', '0002_alter_datememo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datememo',
            name='date',
            field=models.DateField(),
        ),
    ]
