# Generated by Django 5.0.6 on 2024-07-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_is_checked_alter_schedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
