# Generated by Django 5.0.6 on 2024-07-17 06:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemoduls', '0002_rename_schedulemodul_schedulemodule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleModule',
            new_name='ScheduleModul',
        ),
    ]
